### ISSUE TITLE
carwings error INVALID PARAMS: 404

### ISSUE THREAD

**Issue by rerpires** [remuslazar/homeassistant-carwings#79]
## System Information

version | core-2025.1.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.13.1
os_name | Linux
os_version | 6.6.66-haos
arch | x86_64
timezone | Europe/Lisbon
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
HACS Data | ok
GitHub API Calls Remaining | 5000
Installed Version | 2.0.3
Stage | running
Available Repositories | 1500
Downloaded Repositories | 11

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 14.1
-- | --
update_channel | stable
supervisor_version | supervisor-2024.12.3
agent_version | 1.6.0
docker_version | 27.2.0
disk_total | 219.4 GB
disk_used | 17.7 GB
healthy | true
supported | true
host_connectivity | true
supervisor_connectivity | true
ntp_synchronized | true
virtualization | 
board | generic-x86-64
supervisor_api | ok
version_api | ok
installed_addons | Cloudflared (5.2.7), Advanced SSH & Web Terminal (20.0.0), Mosquitto broker (6.5.0), Network UPS Tools (0.14.0), Samba Backup (5.2.0), File editor (5.8.0)

</details>

<details><summary>Dashboards</summary>

dashboards | 2
-- | --
resources | 5
views | 6
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 11, 2024 at 17:51
-- | --
current_recorder_run | January 14, 2025 at 12:28
estimated_db_size | 2786.11 MiB
database_engine | sqlite
database_version | 3.47.1

</details>

<details><summary>Sonoff</summary>

version | 3.8.1 (ffa7e22)
-- | --
cloud_online | 1 / 1
local_online | 1 / 1

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/remuslazar/homeassistant-nissan-carwings/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

Hi, 

Since yesterday I'm getting the following error: 

This error originated from a custom integration.

Logger: pycarwings3.pycarwings3
Source: custom_components/nissan_carwings/api.py:170
integration: Nissan Connect (Carwings) (documentation, issues)
First occurred: 12:29:07 (11 occurrences)
Last logged: 12:34:35

carwings error INVALID PARAMS: 404

and 

This error originated from a custom integration.

Logger: custom_components.nissan_carwings
Source: custom_components/nissan_carwings/api.py:180
integration: Nissan Connect (Carwings) (documentation, issues)
First occurred: 12:29:07 (11 occurrences)
Last logged: 12:34:35

Error fetching battery status - CarwingsError: INVALID PARAMS

### Reproduction steps

Always. Even after reboot 

### Debug logs

```text
2025-01-14 12:39:44.410 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:39:44.410 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsClimateDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:39:44.410 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDrivingAnalysisDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:39:44.410 INFO (MainThread) [custom_components.nissan_carwings] Starting Nissan Carwings integration for user=rerpires@gmail.com
2025-01-14 12:39:44.560 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:39:46.638 ERROR (MainThread) [pycarwings3.pycarwings3] carwings error INVALID PARAMS: 404
2025-01-14 12:39:46.639 ERROR (MainThread) [custom_components.nissan_carwings] Error fetching battery status - CarwingsError: INVALID PARAMS
2025-01-14 12:39:46.639 DEBUG (MainThread) [custom_components.nissan_carwings] Finished fetching nissan_carwings data in 2.229 seconds (success: False)
2025-01-14 12:39:49.570 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:39:51.779 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:39:51.779 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsClimateDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:39:51.780 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDrivingAnalysisDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:39:51.780 INFO (MainThread) [custom_components.nissan_carwings] Starting Nissan Carwings integration for user=rerpires@gmail.com
2025-01-14 12:39:54.013 ERROR (MainThread) [pycarwings3.pycarwings3] carwings error INVALID PARAMS: 404
2025-01-14 12:39:54.014 ERROR (MainThread) [custom_components.nissan_carwings] Error fetching battery status - CarwingsError: INVALID PARAMS
2025-01-14 12:39:54.015 DEBUG (MainThread) [custom_components.nissan_carwings] Finished fetching nissan_carwings data in 2.234 seconds (success: False)
2025-01-14 12:39:54.572 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:39:59.574 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:40:04.409 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:40:04.410 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsClimateDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:40:04.410 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDrivingAnalysisDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:40:04.411 INFO (MainThread) [custom_components.nissan_carwings] Starting Nissan Carwings integration for user=rerpires@gmail.com
2025-01-14 12:40:04.576 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:40:06.622 ERROR (MainThread) [pycarwings3.pycarwings3] carwings error INVALID PARAMS: 404
2025-01-14 12:40:06.622 ERROR (MainThread) [custom_components.nissan_carwings] Error fetching battery status - CarwingsError: INVALID PARAMS
2025-01-14 12:40:06.623 DEBUG (MainThread) [custom_components.nissan_carwings] Finished fetching nissan_carwings data in 2.212 seconds (success: False)
2025-01-14 12:40:09.577 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:40:14.579 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:40:19.582 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:40:24.587 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:40:27.080 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:40:27.080 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsClimateDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:40:27.081 DEBUG (MainThread) [custom_components.nissan_carwings] <class 'custom_components.nissan_carwings.coordinator.CarwingsDrivingAnalysisDataUpdateCoordinator'> initialized with update interval 0:05:00
2025-01-14 12:40:27.081 INFO (MainThread) [custom_components.nissan_carwings] Starting Nissan Carwings integration for user=rerpires@gmail.com
2025-01-14 12:40:29.295 ERROR (MainThread) [pycarwings3.pycarwings3] carwings error INVALID PARAMS: 404
2025-01-14 12:40:29.295 ERROR (MainThread) [custom_components.nissan_carwings] Error fetching battery status - CarwingsError: INVALID PARAMS
2025-01-14 12:40:29.296 DEBUG (MainThread) [custom_components.nissan_carwings] Finished fetching nissan_carwings data in 2.214 seconds (success: False)
2025-01-14 12:40:29.584 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
2025-01-14 12:40:34.596 WARNING (MainThread) [custom_components.localtuya.common] Missing device configuration for device_id bf4c0233ee72a1009f4swh
```

**Comment by mihaicristianpetrescu** [comment]
I can confirm the same problem happening on my end as well. Latest HA Core, it started out of the blue, after a HA restart.

**Comment by Ni3kjm** [comment]
Yep,  same here after a random restart

**Comment by wildcard5** [comment]
I think their servers are unstable at the moment and if you do a restart when they are down it will throw that error
Screen of recent 'carwings' contact
![Screenshot 2025-01-14 131515](https://github.com/user-attachments/assets/1869e07b-0cf3-448a-a7aa-270cf1590106)

**Comment by AlphaZuluNRW** [comment]
I have the same problem after restarting HA. But I can access the Nissan servers at any time via the “Nissan EV app” or “My Leaf”. I have just restarted HA twice, but it still says that the leaf cannot be reached.

**Comment by wildcard5** [comment]
I wonder if the server address has changed again

**Comment by philosoma** [comment]
My Leaf also stopped working when this did, but today My Leaf is working again.

**Comment by badi19** [comment]
The same here. Last weekend bad responses from the Nissan server. Nissan Ev app and My Leaf having trouble also. 
Now this error, but Nissan Ev and My Leaf are working.

**Comment by Enough64** [comment]
Nissan EV has stopped working now. It's probably an update at Nissan..

**Comment by AlphaZuluNRW** [comment]
Nissan EV still works for me (location: Germany), but even slower than usual. And My Leaf also works...

**Comment by Flyer152** [comment]
I'm also having the same issues (UK). Just just to add that i can log into the app and You+Nissan site. I can't get an update from the app, but I can trigger an update from. The you+nissan site. Also to note, I removed the account and tried to re-add, but the it was saying the login info was wrong and couldn't connect, which I knew the login infi was correct.

**Comment by Houimli** [comment]
The same error, i updated the latest version of HACS in the morning, it didn't work after restarting. EU.

**Comment by badi19** [comment]
Nissan ev and myleaf both need a very long time to connect. Sometimes a second try is needed. Maybe the connection timeout has to be set a little longer?

**Comment by nocalla** [comment]
Same issue here, EU also.

**Comment by josemi73** [comment]
Hi
HAOS core-2025.1.2, Leaf integration is working, _**but I have not updated HACS 2.0.3 yet**_. I suppose that if I restart HAOS (regardless if I update HACS or not), it will fail as yours do.
EU also.

**Comment by Enough64** [comment]
Hm, mine also failed immediately after installing latest HACS. I thought HACS only were an install-framework and didn't influence the app once it is installed. Am I missing something?

**Comment by remuslazar** [comment]
I will take a look into that. Currently being busy with other tasks this could take some some, though..

**Comment by catalin-badea** [comment]
> Hm, mine also failed immediately after installing latest HACS. I thought HACS only were an install-framework and didn't influence the app once it is installed. Am I missing something?

I've downgraded HACS to 2.0.2, however the integration is still broken. I've tries re-configuring the credentials, however it says "Authentication failed. Please check your credentials.". In the logs it's the same error initially reported: "Error fetching battery status - CarwingsError: INVALID PARAMS"

**Comment by mihaicristianpetrescu** [comment]
Ideally someone who can sniff the internet trafic from Android/iOS apps can validate what the API of use is and response.
Right now if you try to hit https://gdcportalgw.its-mo.com/api_v230317_NE/gdc/InitialApp_v2.php you get exactly the same error that HA reports "{"status":404,"message":"INVALID PARAMS"}" - Which is not found...

**Comment by catalin-badea** [comment]
> Ideally someone who can sniff the internet trafic from Android/iOS apps can validate what the API of use is and response. Right now if you try to hit https://gdcportalgw.its-mo.com/api_v230317_NE/gdc/InitialApp_v2.php you get exactly the same error that HA reports "{"status":404,"message":"INVALID PARAMS"}" - Which is not found...

This will only work if the Android / iOS apps will communicate directly to the Carwings API, not with a wrapper on the app's server

**Comment by mihaicristianpetrescu** [comment]
They work directly with the exposed API from Nissan. You can check the codebase of My Leaf app for example, it's open source.

**Comment by mihaicristianpetrescu** [comment]
Yes, and they are. My Leaf hasn't received any updates recently and the API endpoint is the same...problem is I haven't logged out of My Leaf nor am I going to until this gets back to proper working order...otherwise I might be left out of My Leaf as well....

**Comment by catalin-badea** [comment]
> Yes, and they are. My Leaf hasn't received any updates recently and the API endpoint is the same...problem is I haven't logged out of My Leaf nor am I going to until this gets back to proper working order...otherwise I might be left out of My Leaf as well....

Yes, I've checked now as well and it's the same URL (odd). I found out MyLeaf last night and it's working fine, even after logout :)

**Comment by andbad** [comment]
Some year ago I remember a problem with useragent. 

By(t)e

**Comment by badi19** [comment]
Not working on HACS 2.0.2.  and HAOS 2024.12.5.

**Comment by enluring** [comment]
Same for me, hasos 2024.12.5

**Comment by Enough64** [comment]
Hmm, I just tried installing pycarwings3 and ran it manually. No problem, it can login and get the state. Really weird!

**Comment by remuslazar** [comment]
there could be an issue with the current API timeout settings, will check that!

**Comment by TA2k** [comment]
It looks like they check for a valid user-agent. What is the user-agent of the app ?

**Comment by catalin-badea** [comment]
> It looks like they check for a valid user-agent. What is the user-agent of the app ?

Not sure if this is the cause. For example from Postman it's still working, even if I don't pass the User-Agent header

**Comment by TA2k** [comment]
I have with postman the same error

**Comment by catalin-badea** [comment]
> I have with postman the same error

Maybe you're doing something wrong. On my side works just fine from Postman.

What endpoint are you trying?

**Comment by catalin-badea** [comment]
![Image](https://github.com/user-attachments/assets/75b2af10-e1e5-479a-8e56-c018b23cffa7)

![Image](https://github.com/user-attachments/assets/024ead45-b7eb-4654-a1b9-c9eef95cc859)

**Comment by TA2k** [comment]
The issue is UserLoginRequest.php not InitialApp_v2.php

**Comment by catalin-badea** [comment]
> The issue is UserLoginRequest.php not InitialApp_v2.php

It's working just fine with UserLoginRequest.php as well with the same call structure that I've mentioned (no User-Agent header, x-www-form-urlencoded request body).

I've actually tried other endpoints as well

**Comment by MoJo2600** [comment]
I found the problem!

The issue is the UserAgent header that is set by default in the homeassistant aiohttp client. Problem is, think this has to be fixed in the pycarwings3 lib. I opened a pull request for it here.

In detail the problem lies in line 188 of  [`pycarwings3.py`](https://github.com/ev-freaks/pycarwings3/blob/master/pycarwings3/pycarwings3.py)

The original code is like this:

```python
...
    # Nissan servers sometimes do not respond.
    # Connections seem OK, but reads are slow and may not be successful
    async with self.session.post(url, data=params) as response:
        log.debug(
...
```

We would need to override the headers here like this:

```python
...
    # Nissan servers sometimes do not respond.
    # Connections seem OK, but reads are slow and may not be successful
    async with self.session.post(url, data=params, headers=[]) as response:
        log.debug(
...
```

Homeassistant makes it clear, that the user has to overwrite the headers in the request method. See [aiohttp_client.py](https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/aiohttp_client.py)

```
# Prevent packages accidentally overriding our default headers
# It's important that we identify as Home Assistant
# If a package requires a different user agent, override it by passing a headers
# dictionary to the request method.
clientsession._default_headers = MappingProxyType(  # type: ignore[assignment]  # noqa: SLF001
    {USER_AGENT: SERVER_SOFTWARE},
)
```

As this component does not have access to the request method in the pycarwings3 lib, the fix has to be made there, I think.

My workaround now is to put a patched copy of the pycarwings3.py into my home assistant installation. This should work until everything is fixed.

**Comment by kriskomp** [comment]
> I found the problem!
> 
> The issue is the UserAgent header that is set by default in the homeassistant aiohttp client. Problem is, think this has to be fixed in the pycarwings3 lib. I opened a pull request for it [here](https://github.com/ev-freaks/pycarwings3/pull/10).
> 
> In detail the problem lies in line 188 of [`pycarwings3.py`](https://github.com/ev-freaks/pycarwings3/blob/master/pycarwings3/pycarwings3.py)
> 
> The original code is like this:
> 
> ...
>     # Nissan servers sometimes do not respond.
>     # Connections seem OK, but reads are slow and may not be successful
>     async with self.session.post(url, data=params) as response:
>         log.debug(
> ...
> We would need to override the headers here like this:
> 
> ...
>     # Nissan servers sometimes do not respond.
>     # Connections seem OK, but reads are slow and may not be successful
>     async with self.session.post(url, data=params, headers=[]) as response:
>         log.debug(
> ...
> Homeassistant makes it clear, that the user has to overwrite the headers in the request method. See [aiohttp_client.py](https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/aiohttp_client.py)
> 
> ```
> # Prevent packages accidentally overriding our default headers
> # It's important that we identify as Home Assistant
> # If a package requires a different user agent, override it by passing a headers
> # dictionary to the request method.
> clientsession._default_headers = MappingProxyType(  # type: ignore[assignment]  # noqa: SLF001
>     {USER_AGENT: SERVER_SOFTWARE},
> )
> ```
> 
> As this component does not have access to the request method in the pycarwings3 lib, the fix has to be made there, I think.
> 
> My workaround now is to put a patched copy of the pycarwings3.py into my home assistant installation. This should work until everything is fixed.

I have dummy question, where can I found pycarwings3.py?

**Comment by Enough64** [comment]
Where is this file located? I did "docker exec -it homeassistant bash" and changed the file /usr/local/lib/python3.13/site-packages/pycarwings3/pycarwings3.py and cleared the pycache but it still didn't work.

**Comment by mihaicristianpetrescu** [comment]
> I found the problem!
> 
> The issue is the UserAgent header that is set by default in the homeassistant aiohttp client. Problem is, think this has to be fixed in the pycarwings3 lib. I opened a pull request for it [here](https://github.com/ev-freaks/pycarwings3/pull/10).
> 
> In detail the problem lies in line 188 of [`pycarwings3.py`](https://github.com/ev-freaks/pycarwings3/blob/master/pycarwings3/pycarwings3.py)
> 
> The original code is like this:
> 
> ...
>     # Nissan servers sometimes do not respond.
>     # Connections seem OK, but reads are slow and may not be successful
>     async with self.session.post(url, data=params) as response:
>         log.debug(
> ...
> We would need to override the headers here like this:
> 
> ...
>     # Nissan servers sometimes do not respond.
>     # Connections seem OK, but reads are slow and may not be successful
>     async with self.session.post(url, data=params, headers=[]) as response:
>         log.debug(
> ...
> Homeassistant makes it clear, that the user has to overwrite the headers in the request method. See [aiohttp_client.py](https://github.com/home-assistant/core/blob/dev/homeassistant/helpers/aiohttp_client.py)
> 
> ```
> # Prevent packages accidentally overriding our default headers
> # It's important that we identify as Home Assistant
> # If a package requires a different user agent, override it by passing a headers
> # dictionary to the request method.
> clientsession._default_headers = MappingProxyType(  # type: ignore[assignment]  # noqa: SLF001
>     {USER_AGENT: SERVER_SOFTWARE},
> )
> ```
> 
> As this component does not have access to the request method in the pycarwings3 lib, the fix has to be made there, I think.
> 
> My workaround now is to put a patched copy of the pycarwings3.py into my home assistant installation. This should work until everything is fixed.

Did the change, restart HA - didn't fix the problem. Rebooted the system running HA...same problem.

**Comment by MoJo2600** [comment]
Yes, I was too quick. Sorry. The error is the User Agent in the headers. But simply setting them to an empty array does not fix the issue. HA is setting default headers, they will always be added to the client. I removed the hass aio client (the call to `async_create_clientsession`) from the integration altogether when i wrote my comment and and then it was working. I'm trying this fix now, but it is only working in my test environment. Not in my home assistant installation. I created a fork and I'm trying to get it working. https://github.com/MoJo2600/homeassistant-carwings

**Comment by MoJo2600** [comment]
Ok, I think I got it working

<img width="743" alt="Image" src="https://github.com/user-attachments/assets/39ce4280-3a2f-4cd6-8572-ce48e4f007dd" />

Would anybody test it with my fork to confirm? I'm not sure if my solution to just remove the HA aio http client is a good solution, but it seems to do the job.

**Comment by Enough64** [comment]
Yes, it is working for me also !

**Comment by mihaicristianpetrescu** [comment]
Did the 2 changes as well in my local HACS custom add-on and it's working. I also had the other change in pycarwings3 though...is that still required? I would think not considering the change from the actual add-on.

**Comment by MoJo2600** [comment]
> Did the 2 changes as well in my local HACS custom add-on and it's working. I also had the other change in pycarwings3 though...is that still required? I would think not considering the change from the actual add-on.

No, only the changes I made in my pull request are needed.

**Comment by kriskomp** [comment]
> > Did the 2 changes as well in my local HACS custom add-on and it's working. I also had the other change in pycarwings3 though...is that still required? I would think not considering the change from the actual add-on.
> 
> No, only the changes I made in my pull request are needed.

Very thanks, it also work for me!

**Comment by kriskomp** [comment]
> Where is this file located? I did "docker exec -it homeassistant bash" and changed the file /usr/local/lib/python3.13/site-packages/pycarwings3/pycarwings3.py and cleared the pycache but it still didn't work.

Thanks a lot!

**Comment by Flyer152** [comment]
Would anybody test it with my fork to confirm? I'm not sure if my solution to just remove the HA aio http client is a good solution, but it seems to do the job.

I have just removed the previous intergrating and deleated it form HACS. downloaded your "fork" version and I can now login download data from the Nissan server. 
but, Im unable to start the climate control or "request an update". will see how the overnight charge up goes this evening.

Thanks for your help.

**Comment by MoJo2600** [comment]
> Would anybody test it with my fork to confirm? I'm not sure if my solution to just remove the HA aio http client is a good solution, but it seems to do the job.
> 
> I have just removed the previous intergrating and deleated it form HACS. downloaded your "fork" version and I can now login download data from the Nissan server. but, Im unable to start the climate control or "request an update". will see how the overnight charge up goes this evening.
> 
> Thanks for your help.

I tried to start climate control right now and the car was not responding. But I did get a notification that the ac stopped from the Nissan app when I turned it off in HA. So the message seems to be sent successfully. I'll try to debug this as well.

**Comment by Enough64** [comment]
I also tried starting climate control control twice. It worked both times for me, I think. I got notifications in the Nissan App, both start and end, but I'm not sure if it actually started the first time. But that's probably not the integration's fault.

**Comment by badi19** [comment]
About the climate control: I always find this part a little buggy. When switching it on, I can't rely on it having activated the climate control in the car. Sometimes it gets suddenly shown as active as well, without me having activated the climate control. But I am not sure whether this comes from Nissan or this integration. Lately I tried to test it: I activated  CC through the Nissan app. Then activated the car, so the CC is turned off. I expected that the Nissan app would show an inactive CC, but didn't. MyLeaf: also showed CC is on. On the other hand, this integration showes CC is off. 

Strange. So I thought: lets wait till this integration suddenly shows an activated CC, and then check the official app. But it didn't happen again so far.
I do know: after restart HA the CC is shown off again.

**Comment by catalin-badea** [comment]
Everything is working on my side as well with @MoJo2600 's branch, even the climate control, which actually started in the car from the first try.

Very odd that the Nissan Carwings API accepts requests with no User-Agent header at all, but not with the specific one used by HASS.

Thank you for going further with the investigation!

**Comment by andbad** [comment]
> Yes, I was too quick. Sorry. The error is the User Agent in the headers. But simply setting them to an empty array does not fix the issue. HA is setting default headers, they will always be added to the client. I removed the hass aio client (the call to `async_create_clientsession`) from the integration altogether when i wrote my comment and and then it was working. I'm trying this fix now, but it is only working in my test environment. Not in my home assistant installation. I created a fork and I'm trying to get it working. https://github.com/MoJo2600/homeassistant-carwings

This fork works for me. I haven't tested A/C.

By(t)e

**Comment by MoJo2600** [comment]
Ok, good to hear that it is working. I hope @remuslazar will have a look at this soon. Then I will close my fork again.

**Comment by andbad** [comment]
I tested also the A/C, no problem with my old 2016 Leaf.

By(t)e

**Comment by X3m2010** [comment]
At first it worked for me, but then again I got this in the protocol after the next update:

carwings error INVALID PARAMS: -2000
Error fetching battery status - CarwingsError: INVALID PARAMS
carwings error INVALID PARAMS: -2000
Error fetching climate data - CarwingsError: INVALID PARAMS
Error fetching nissan_carwings data: Error fetching driving analysis data - KeyError: 'ElectricMileageLevel'
Error fetching nissan_carwings data: Error fetching battery status - CarwingsError: INVALID PARAMS
Error fetching nissan_carwings data: Error fetching climate data - CarwingsError: INVALID PARAMS
Error fetching driving analysis data - KeyError: 'ElectricMileageLevel'

My settings are for Northern Europe, if this matters.

**Comment by catalin-badea** [comment]
> At first it worked for me, but then again I got this in the protocol after the next update:
> 
> carwings error INVALID PARAMS: -2000 Error fetching battery status - CarwingsError: INVALID PARAMS carwings error INVALID PARAMS: -2000 Error fetching climate data - CarwingsError: INVALID PARAMS Error fetching nissan_carwings data: Error fetching driving analysis data - KeyError: 'ElectricMileageLevel' Error fetching nissan_carwings data: Error fetching battery status - CarwingsError: INVALID PARAMS Error fetching nissan_carwings data: Error fetching climate data - CarwingsError: INVALID PARAMS Error fetching driving analysis data - KeyError: 'ElectricMileageLevel'
> 
> My settings are for Northern Europe, if this matters.

I've forced an update and I don't have any issues so far

**Comment by X3m2010** [comment]
It seems unstable, but it's working again. Better than before at least. 😂
I will keep an eye on it, and update the post.

Thx so far for your input!


Regards
Markus

(von unterwegs, mit meinem Smartphone gesendet)

catalin-badea ***@***.***> schrieb am Fr., 17. Jän. 2025,
09:40:

**Comment by zekje** [comment]
@MoJo2600 , i have tried your fork , it's seem to be ok for me .  (EU 2018 version in france )

**Comment by remuslazar** [comment]
Hello everybody!

Thanks a lot for the debugging and also for the pull request!

I was able to fix the issue by fixing the pycarwings3 library. Doing so we can reuse the existing aiohttp session from HASS which has some benefits.

I have also published a new release of pycarwings3 (0.7.12) which should fix the issue.

A HASS restart should fix the issue by picking up the 0.7.12 version of the library.

I will reopen this issue now (it was auto-closed by mistake, sorry for that) until I get some positive feedback that this works. If not, I could create a patch level release which pins the pycarwings3 library to >=0.7.12

**Comment by MoJo2600** [comment]
Very good @remuslazar your fix is better than mine! Thanks a lot!

**Comment by SamKua** [comment]
Not sure if I'm doing something wrong, I've restarted Home Assistant, that didn't fix anything, so I told it to redownload the Carwings addin in HACS and tried again, but its still not working for me. Do I need to do something else?

**Comment by remuslazar** [comment]
> Not sure if I'm doing something wrong, I've restarted Home Assistant, that didn't fix anything, so I told it to redownload the Carwings addin in HACS and tried again, but its still not working for me. Do I need to do something else?

I will create a minor release which pins the library, this should then work reliably.

**Comment by mihaicristianpetrescu** [comment]
> Hello everybody!
> 
> Thanks a lot for the debugging and also for the pull request!
> 
> I was able to fix the issue by [fixing](https://github.com/ev-freaks/pycarwings3/pull/11) the pycarwings3 library. Doing so we can reuse the existing aiohttp session from HASS which has some benefits.
> 
> I have also published a new release of pycarwings3 (0.7.12) which should fix the issue.
> 
> A HASS restart should fix the issue by picking up the 0.7.12 version of the library.
> 
> I will reopen this issue now (it was auto-closed by mistake, sorry for that) until I get some positive feedback that this works. If not, I could create a patch level release which pins the pycarwings3 library to >=0.7.12

Reverted previous changes suggested by @MoJo2600 and manually applied just your change in pycarwings3.
Seems to be working.
Not sure how exactly can the system be forced to show that an update is available for pycarwings3 so people don't have to SUDO and change the code on their own.

**Comment by remuslazar** [comment]
I have created a new release (https://github.com/remuslazar/homeassistant-carwings/releases/tag/v0.4.2) which pins the pycarwings3 lib to the current version. A simple update of the extension using HACS should fix the issue reliably.

@mihaicristianpetrescu just update the integration to 0.4.2, no need to sudo or to do weird stuff.

**Comment by mihaicristianpetrescu** [comment]
@remuslazar Already did but I'll update the HACS integration as well and then the codebase will be in sync.

**Comment by SamKua** [comment]
Updated via HACS, all working again now. Thank you so much!

**Comment by aloisdecroon** [comment]
Working again after update to 0.4.2

Thanks!

**Comment by remuslazar** [comment]
🍻

**Comment by andbad** [comment]
The new version works. Thanks to all, 

By(t)e

**Comment by 0i5e4u** [comment]
Thanks for rescuing my Leaf. Already searched for some other Brand where API issnt such an husle^^

;)

**Comment by remuslazar** [comment]
> Thanks for rescuing my Leaf. Already searched for some other Brand where API issnt such an husle^^
> 
> ;)

Newer Leafs (model year 2019+) use a new, much better API (see https://github.com/dan-r/HomeAssistant-NissanConnect). The new "NissanConnect" API (without the "EV" suffix) works much better and has many additional features, also the updates are much faster (a couple of seconds instead of minutes).

**Comment by StephB67** [comment]
The new version works. 

Thanks to all

**Comment by iamagit** [comment]
This unofficial integration is fab and allow me to use HA to charge my leaf to what ever level I would like. So very grateful remuslazar that you maintain it and fixed this recent change by Nissan super fast.

**Comment by josemi73** [comment]
Thank you @remuslazar for your great carwings repository, I have just paid a coffee for you, if you come to Spain, may be you could have 2 or 3. Even with tapa :-)
With HA, smart plug, electric meter and your integration, I am avoiding to install a wallbox so far.

[buymeacoffee.com/remuslazar](url)

**Comment by Flyer152** [comment]
Hi, does anyone know how to change the carwings accound password in the intergration? Other than delete and reload. Thanks.
